name: DeathChest
version: '${project.version}'
main: me.pancaketaste.deathchest.DeathChest
api-version: '1.17'
commands:
  deathctp:
    description: Teleport to death chest.
    permissions:
      deathc.tp